In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


In [6]:
data= {'x1':[13,18,17,20,22,21],
      'x2':[9,7,17,11,8,10],
      'y':[20,22,30,27,35,32]}

In [7]:
data = pd.DataFrame(data)

In [9]:
x= data[['x1','x2']]
y = data['y']

In [10]:
data

x1  x2   y
0  13   9  20
1  18   7  22
2  17  17  30
3  20  11  27
4  22   8  35
5  21  10  32

In [12]:
lr = LinearRegression()

In [13]:
lr.fit(x,y)

LinearRegression()

In [14]:
y_pred = lr.predict(x)

In [15]:
lr.intercept_

-7.359201773835938

In [16]:
lr.coef_

array([1.5443459 , 0.62472284])

# 적합도 검증

In [19]:
from sklearn.metrics import mean_squared_error

In [20]:
lr.score(x,y)

0.7969440176685232

In [21]:
mean_squared_error(y,y_pred)

5.730691056910565

In [22]:
mean_squared_error(y,y_pred)**0.5

2.393886182948255

In [23]:
from sklearn.datasets import load_boston

In [24]:
bt = load_boston()

In [25]:
x=pd.DataFrame(bt.data,columns=bt.feature_names)

In [27]:
y=bt.target

In [29]:
lr.fit(x,y)

LinearRegression()

In [31]:
y_pred2 = lr.predict(x)

In [35]:
lr.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [36]:
lr.intercept_

36.45948838509011

In [32]:
lr.score(x,y)

0.7406426641094095

In [33]:
mean_squared_error(y,y_pred2)

21.894831181729202

In [34]:
mean_squared_error(y,y_pred2)**0.5

4.679191295697281

In [37]:
from sklearn.datasets import load_diabetes

In [38]:
diabetes = load_diabetes()

In [43]:
x = pd.DataFrame(diabetes.data,columns=diabetes.feature_names)

In [45]:
y = diabetes.target

In [47]:
lr.fit(x,y)

LinearRegression()

In [48]:
y_pred3 = lr.predict(x)

In [50]:
lr.intercept_

152.1334841628965

In [51]:
lr.coef_

array([ -10.01219782, -239.81908937,  519.83978679,  324.39042769,
       -792.18416163,  476.74583782,  101.04457032,  177.06417623,
        751.27932109,   67.62538639])

In [52]:
lr.score(x,y)

0.5177494254132934

In [53]:
mean_squared_error(y,y_pred3)

2859.6903987680657

In [54]:
mean_squared_error(y,y_pred3)**0.5

53.47607314274362