In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
iris = load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
iris_data = iris['data']

In [5]:
a=iris.data

In [6]:
iris_label = iris['target']

In [7]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
df = pd.DataFrame(data=iris_data, columns=iris['feature_names'])

In [9]:
df['label'] = iris_label

In [10]:
# 0 : 'setosa', 1:'versicolor', 2:'virginica'
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [11]:
feature_names = df.columns.tolist()[:-1]

In [12]:
X = df[feature_names]

In [13]:
y=df['label']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.3, random_state=121)

In [15]:
model = DecisionTreeClassifier(random_state=121)

In [16]:
model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=121)

In [17]:
y_predict = model.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_test,y_predict)

0.9555555555555556

In [20]:
y_test

50     1
148    2
85     1
6      0
32     0
92     1
64     1
79     1
59     1
141    2
70     1
53     1
58     1
47     0
29     0
136    2
62     1
25     0
115    2
5      0
111    2
146    2
78     1
98     1
90     1
89     1
49     0
23     0
131    2
102    2
86     1
118    2
28     0
43     0
74     1
109    2
48     0
18     0
20     0
134    2
123    2
138    2
137    2
19     0
106    2
Name: label, dtype: int32

In [21]:
y_predict

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2, 1, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 2, 2, 0,
       1])

In [22]:
(y_test == y_predict).sum()/len(y_test)

0.9555555555555556

In [23]:
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.model_selection import GridSearchCV

In [24]:
scores = cross_val_score(model,X,y,scoring='accuracy',cv=3)

In [25]:
np.round(scores,4)

array([0.98, 0.94, 0.98])

In [26]:
max_depth = np.random.randint(1,20,10)
max_features = np.random.uniform(0.3,1.0,10)
min_samples_split= [2,3]

In [27]:
parameters = {'max_depth':max_depth,'max_features':max_features,'min_samples_split':min_samples_split}

In [28]:
grid_dtree = GridSearchCV(model,
            param_grid=parameters,
            cv=3,
            refit=True)

In [29]:
grid_dtree.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=121),
             param_grid={'max_depth': array([13, 14,  9,  1, 15,  7,  5,  7,  8, 17]),
                         'max_features': array([0.30980197, 0.77275122, 0.58659188, 0.81318298, 0.74702723,
       0.58633469, 0.3534835 , 0.53183455, 0.54073259, 0.97711949]),
                         'min_samples_split': [2, 3]})

In [30]:
df = pd.DataFrame(grid_dtree.cv_results_)

In [31]:
df.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.003254  4.596267e-04         0.001627        0.000460   
1       0.002279  4.615361e-04         0.001625        0.000462   
2       0.002928  2.973602e-07         0.001626        0.000920   
3       0.002603  4.599627e-04         0.001627        0.000461   
4       0.002603  4.601875e-04         0.001301        0.000460   

  param_max_depth param_max_features param_min_samples_split  \
0              13           0.309802                       2   
1              13           0.309802                       3   
2              13           0.772751                       2   
3              13           0.772751                       3   
4              13           0.586592                       2   

                                              params  split0_test_score  \
0  {'max_depth': 13, 'max_features': 0.3098019708...           0.914286   
1  {'max_depth': 13, 'max_features': 0.3098019708...           0.914286   
2  {'max_depth': 13, 'max_features': 0.7727512170...           0.942857   
3  {'max_depth': 13, 'max_features': 0.7727512170...           0.942857   
4  {'max_depth': 13, 'max_features': 0.5865918833...           0.942857   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0           0.885714           0.942857         0.914286        0.023328   
1           0.914286           0.942857         0.923810        0.013469   
2           0.914286           0.942857         0.933333        0.013469   
3           0.914286           0.942857         0.933333        0.013469   
4           0.828571           0.971429         0.914286        0.061721   

   rank_test_score  
0               73  
1               55  
2                1  
3                1  
4               73

In [32]:
df_sort = df.sort_values(by='rank_test_score')

In [33]:
df_sort['params']

99     {'max_depth': 15, 'max_features': 0.9771194871...
122    {'max_depth': 5, 'max_features': 0.77275121709...
119    {'max_depth': 7, 'max_features': 0.97711948714...
118    {'max_depth': 7, 'max_features': 0.97711948714...
107    {'max_depth': 7, 'max_features': 0.81318297857...
                             ...                        
67     {'max_depth': 1, 'max_features': 0.81318297857...
65     {'max_depth': 1, 'max_features': 0.58659188330...
64     {'max_depth': 1, 'max_features': 0.58659188330...
71     {'max_depth': 1, 'max_features': 0.58633468773...
79     {'max_depth': 1, 'max_features': 0.97711948714...
Name: params, Length: 200, dtype: object

In [34]:
df_sort

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
99        0.001953  4.052337e-07         0.000976    6.836514e-07   
122       0.002278  4.613116e-04         0.001301    4.607494e-04   
119       0.001952  1.123916e-07         0.001301    4.600188e-04   
118       0.001952  1.123916e-07         0.000976    0.000000e+00   
107       0.001954  1.469711e-06         0.001626    4.599071e-04   
..             ...           ...              ...             ...   
67        0.002277  4.608059e-04         0.001290    4.436096e-04   
65        0.001952  2.213858e-06         0.001303    4.608057e-04   
64        0.002276  4.589511e-04         0.000977    1.140650e-06   
71        0.002277  4.600188e-04         0.001301    4.600750e-04   
79        0.001952  1.946680e-07         0.001301    4.600188e-04   

    param_max_depth param_max_features param_min_samples_split  \
99               15           0.977119                       3   
122               5           0.772751                       2   
119               7           0.977119                       3   
118               7           0.977119                       2   
107               7           0.813183                       3   
..              ...                ...                     ...   
67                1           0.813183                       3   
65                1           0.586592                       3   
64                1           0.586592                       2   
71                1           0.586335                       3   
79                1           0.977119                       3   

                                                params  split0_test_score  \
99   {'max_depth': 15, 'max_features': 0.9771194871...           0.942857   
122  {'max_depth': 5, 'max_features': 0.77275121709...           0.942857   
119  {'max_depth': 7, 'max_features': 0.97711948714...           0.942857   
118  {'max_depth': 7, 'max_features': 0.97711948714...           0.942857   
107  {'max_depth': 7, 'max_features': 0.81318297857...           0.942857   
..                                                 ...                ...   
67   {'max_depth': 1, 'max_features': 0.81318297857...           0.657143   
65   {'max_depth': 1, 'max_features': 0.58659188330...           0.657143   
64   {'max_depth': 1, 'max_features': 0.58659188330...           0.657143   
71   {'max_depth': 1, 'max_features': 0.58633468773...           0.657143   
79   {'max_depth': 1, 'max_features': 0.97711948714...           0.657143   

     split1_test_score  split2_test_score  mean_test_score  std_test_score  \
99            0.914286           0.942857         0.933333        0.013469   
122           0.914286           0.942857         0.933333        0.013469   
119           0.914286           0.942857         0.933333        0.013469   
118           0.914286           0.942857         0.933333        0.013469   
107           0.914286           0.942857         0.933333        0.013469   
..                 ...                ...              ...             ...   
67            0.657143           0.657143         0.657143        0.000000   
65            0.657143           0.657143         0.657143        0.000000   
64            0.657143           0.657143         0.657143        0.000000   
71            0.657143           0.657143         0.657143        0.000000   
79            0.657143           0.657143         0.657143        0.000000   

     rank_test_score  
99                 1  
122                1  
119                1  
118                1  
107                1  
..               ...  
67               181  
65               181  
64               181  
71               181  
79               181  

[200 rows x 14 columns]

# 레이블 인코딩

In [35]:
from sklearn.preprocessing import LabelEncoder

In [44]:
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
items1=['호랑이','사자','사자','독수리']

In [45]:
encoder = LabelEncoder()

In [47]:
encoder.fit(items)

LabelEncoder()

In [48]:
encoder.transform(items)

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [40]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

# 원-핫 인코딩, get_dummies()

In [41]:
df1 = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

In [42]:
df1

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [43]:
pd.get_dummies(df1)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0